
networks:
  demo:
    # Specify driver options
    name: demo
    driver: bridge

services:

  echo-server:
    image: ealen/echo-server:0.9.2
    ports:
      - 3000:80
    networks:
      - demo


  postgres:
    image: postgres:15
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - demo

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # KEYCLOAK_ADMIN: admin
      # KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./realm-demo.json:/opt/keycloak/data/import/realm-demo.json
    networks:
      - demo

volumes:
  pg_data: